#!/bin/bash
# Copy Azure configuration from infrastructure folder to Aspire solution
# This script ensures the Aspire solution has access to all connection strings
# and configuration generated by the setup scripts.

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration - adjust these paths as needed
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$SCRIPT_DIR/../../apps/todo-app"
API_DIR="$SCRIPT_DIR/src/TodoApp.Api"

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Copy Azure Configuration to Aspire${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Check if infrastructure config exists
if [ ! -f "$INFRA_DIR/azure-config.json" ]; then
    echo -e "${RED}❌ Infrastructure config not found at: $INFRA_DIR/azure-config.json${NC}"
    echo -e "${YELLOW}Run the setup scripts in apps/todo-app/ first!${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Found infrastructure config${NC}"

# Read values from azure-config.json
DB_SERVER=$(grep -o '"fullyQualifiedName": "[^"]*"' "$INFRA_DIR/azure-config.json" | cut -d'"' -f4)
DB_NAME=$(grep -o '"name": "todo-app-db"' "$INFRA_DIR/azure-config.json" | head -1 | cut -d'"' -f4)
DB_USER=$(grep -o '"adminUser": "[^"]*"' "$INFRA_DIR/azure-config.json" | cut -d'"' -f4)

# Check if .env.local has the password
if [ -f "$INFRA_DIR/.env.local" ]; then
    DB_PASSWORD=$(grep "^DB_PASSWORD=" "$INFRA_DIR/.env.local" | cut -d'=' -f2)
fi

echo ""
echo -e "${YELLOW}Database Configuration:${NC}"
echo -e "  Server: $DB_SERVER"
echo -e "  Database: $DB_NAME"
echo -e "  User: $DB_USER"

# Check if password is set
if [ -z "$DB_PASSWORD" ] || [ "$DB_PASSWORD" == "YOUR_PASSWORD_HERE" ]; then
    echo ""
    echo -e "${YELLOW}⚠️  Database password not set in .env.local${NC}"
    echo -e "${YELLOW}Please enter the SQL admin password:${NC}"
    read -s DB_PASSWORD
    echo ""
    
    if [ -z "$DB_PASSWORD" ]; then
        echo -e "${RED}❌ Password is required${NC}"
        exit 1
    fi
    
    # Update .env.local with the password
    if [ -f "$INFRA_DIR/.env.local" ]; then
        sed -i "s/DB_PASSWORD=YOUR_PASSWORD_HERE/DB_PASSWORD=$DB_PASSWORD/" "$INFRA_DIR/.env.local"
        sed -i "s/Password=YOUR_PASSWORD_HERE/Password=$DB_PASSWORD/g" "$INFRA_DIR/.env.local"
        echo -e "${GREEN}✓ Updated password in $INFRA_DIR/.env.local${NC}"
    fi
fi

# Build connection string
CONNECTION_STRING="Server=tcp:$DB_SERVER,1433;Database=$DB_NAME;User ID=$DB_USER;Password=$DB_PASSWORD;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"

echo ""
echo -e "${YELLOW}Creating appsettings.Development.json...${NC}"

# Create appsettings.Development.json for the API
cat > "$API_DIR/appsettings.Development.json" <<EOF
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning",
      "Microsoft.EntityFrameworkCore": "Warning"
    }
  },
  "ConnectionStrings": {
    "TodoDb": "$CONNECTION_STRING"
  }
}
EOF

echo -e "${GREEN}✓ Created $API_DIR/appsettings.Development.json${NC}"

# Also create a symlink or copy to the Aspire solution root for reference
cp "$INFRA_DIR/azure-config.json" "$SCRIPT_DIR/azure-config.json" 2>/dev/null || true
cp "$INFRA_DIR/azure-static-web-config.json" "$SCRIPT_DIR/azure-static-web-config.json" 2>/dev/null || true

echo -e "${GREEN}✓ Copied azure config files to solution root${NC}"

echo ""
echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Configuration Complete!${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "${GREEN}You can now run the Aspire solution:${NC}"
echo -e "  dotnet run --project TodoApp.AppHost"
echo ""
echo -e "${GREEN}Or apply database migrations:${NC}"
echo -e "  cd src/TodoApp.Api"
echo -e "  dotnet ef database update"
echo ""
